# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2023-09-28 13:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import georef.tasks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.CharField(default=georef.tasks.pkgen, max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='GeometriaRecurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometria', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('idrecurs', models.ForeignKey(blank=True, db_column='idrecurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='georef.Recursgeoref')),
            ],
            options={
                'verbose_name': 'Geometria de recurs de georeferenciació',
            },
        ),
        migrations.CreateModel(
            name='GeometriaToponimVersio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometria', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('idversio', models.ForeignKey(blank=True, db_column='idversio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='georef.Toponimversio')),
            ],
            options={
                'verbose_name': 'Geometria de versió de topònim',
            },
        ),
        migrations.CreateModel(
            name='HelpFile',
            fields=[
                ('id', models.CharField(default=georef.tasks.pkgen, max_length=200, primary_key=True, serialize=False)),
                ('titol', models.TextField()),
                ('h_file', models.FileField(upload_to='helpfile_uploads')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Fitxer d'ajuda",
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=5, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('open_in_outside_tab', models.BooleanField(default=True)),
                ('is_separator', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item del menú',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Organització',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toponim_permission', models.CharField(blank=True, max_length=200, null=True)),
                ('permission_recurs_edition', models.BooleanField(default=False)),
                ('permission_toponim_edition', models.BooleanField(default=False)),
                ('permission_tesaure_edition', models.BooleanField(default=False)),
                ('permission_administrative', models.BooleanField(default=False)),
                ('permission_filter_edition', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georef_addenda.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Perfil d'usuari",
            },
        ),
    ]
