# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-15 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text='The name of the database table for the lookup table', max_length=200)),
                ('table_verbose_name', models.CharField(help_text='The lookup table name which is shown anywhere on the interface', max_length=200)),
                ('locale', models.CharField(help_text='Language of the description', max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
