# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('georef_addenda', '0002_lookupdescription'), ('georef_addenda', '0003_lookupdescription_model_fully_qualified_name'), ('georef_addenda', '0004_auto_20241015_0933'), ('georef_addenda', '0005_auto_20241015_1153')]

    dependencies = [
        ('georef_addenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(help_text='Language of the description', max_length=10)),
                ('description', models.TextField(null=True)),
                ('model_fully_qualified_name', models.CharField(default=None, help_text='The name of the model, in form [package].[name]', max_length=300)),
                ('model_label', models.CharField(default=None, help_text='The label of the lookup. This should be the same as the unstranslated string used for showing the name anywhere in the ui', max_length=200)),
            ],
        ),
    ]
