# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0002_lookupdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupdescription',
            name='model_fully_qualified_name',
            field=models.CharField(help_text='The name of the model, in form [package].[name]', max_length=300, null=True),
        ),
    ]
