# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0002_lookupdescription_squashed_0005_auto_20241015_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupdescription',
            name='locale',
            field=models.CharField(help_text='Language of the description', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lookupdescription',
            name='model_fully_qualified_name',
            field=models.CharField(help_text='The name of the model, in form [package].[name]', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lookupdescription',
            name='model_label',
            field=models.CharField(help_text='The label of the lookup. This should be the same as the unstranslated string used for showing the name anywhere in the ui', max_length=200, null=True),
        ),
    ]
