# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0003_auto_20241016_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometriatoponimversio',
            name='x_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geometriatoponimversio',
            name='x_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geometriatoponimversio',
            name='y_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geometriatoponimversio',
            name='y_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
