# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-15 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0003_lookupdescription_model_fully_qualified_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookupdescription',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='lookupdescription',
            name='table_verbose_name',
        ),
        migrations.AddField(
            model_name='lookupdescription',
            name='model_label',
            field=models.CharField(help_text='The label of the lookup. This should be the same as the unstranslated string used for showing the name anywhere in the ui', max_length=200, null=True),
        ),
    ]
