# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0004_auto_20241015_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupdescription',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lookupdescription',
            name='model_fully_qualified_name',
            field=models.CharField(default=None, help_text='The name of the model, in form [package].[name]', max_length=300),
        ),
        migrations.AlterField(
            model_name='lookupdescription',
            name='model_label',
            field=models.CharField(default=None, help_text='The label of the lookup. This should be the same as the unstranslated string used for showing the name anywhere in the ui', max_length=200),
        ),
    ]
