# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-10-23 14:29
from __future__ import unicode_literals

from django.db import migrations

def update_geometries(apps, schema_editor):
    GeometriaToponimVersio = apps.get_model("georef_addenda", "GeometriaToponimVersio")
    for g in GeometriaToponimVersio.objects.all():
        if g.geometria:
            extent = g.geometria.extent
            g.x_min = extent[0]
            g.y_min = extent[1]
            g.x_max = extent[2]
            g.y_max = extent[3]
            g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0004_auto_20241023_1427'),
    ]

    operations = [
        migrations.RunPython(update_geometries),
    ]
