# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-11-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0005_init_geometry_extents'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
