# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-08-01 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0017_auto_20201116_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('open_in_outside_tab', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Item del menú',
            },
        ),
    ]
