# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-08-01 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0018_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='control_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
