# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-08-02 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0019_menuitem_control_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
