# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-08-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0021_menuitem_is_separator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
