# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-08-02 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0022_auto_20220802_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='control_html',
        ),
    ]
