# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2023-09-28 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georef_addenda', '0001_initial'),
        ('georef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toponim',
            name='idorganization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georef_addenda.Organization'),
        ),
        migrations.AddField(
            model_name='toponim',
            name='idpais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.CASCADE, to='georef.Pais'),
        ),
        migrations.AddField(
            model_name='toponim',
            name='idpare',
            field=models.ForeignKey(blank=True, db_column='idpare', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='georef.Toponim'),
        ),
        migrations.AddField(
            model_name='toponim',
            name='idtipustoponim',
            field=models.ForeignKey(db_column='idtipustoponim', on_delete=django.db.models.deletion.CASCADE, to='georef.Tipustoponim'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='autors',
            field=models.ManyToManyField(through='georef.Autorrecursgeoref', to='georef_addenda.Autor'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='capes_wms_recurs',
            field=models.ManyToManyField(through='georef.Capesrecurs', to='georef.Capawms'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='idambit',
            field=models.ForeignKey(blank=True, db_column='idambit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='georef.Toponimversio'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='idsistemareferenciamm',
            field=models.ForeignKey(blank=True, db_column='idsistemareferenciamm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='georef.Sistemareferenciamm'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='idsuport',
            field=models.ForeignKey(blank=True, db_column='idsuport', null=True, on_delete=django.db.models.deletion.CASCADE, to='georef.Suport'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='idtipusrecursgeoref',
            field=models.ForeignKey(blank=True, db_column='idtipusrecursgeoref', null=True, on_delete=django.db.models.deletion.CASCADE, to='georef.Tipusrecursgeoref'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='idtipusunitatscarto',
            field=models.ForeignKey(blank=True, db_column='idtipusunitatscarto', null=True, on_delete=django.db.models.deletion.CASCADE, to='georef.Tipusunitats'),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='iduser',
            field=models.ForeignKey(blank=True, db_column='iduser', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recursgeoref',
            name='paraulesclau',
            field=models.ManyToManyField(through='georef.ParaulaclauRecurs', to='georef.Paraulaclau'),
        ),
        migrations.AddField(
            model_name='prefsvisibilitatcapes',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.CASCADE, related_name='prefswms', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='paraulaclaurecurs',
            name='idparaula',
            field=models.ForeignKey(db_column='idparaula', on_delete=django.db.models.deletion.CASCADE, to='georef.Paraulaclau'),
        ),
        migrations.AddField(
            model_name='paraulaclaurecurs',
            name='idrecursgeoref',
            field=models.ForeignKey(db_column='idrecursgeoref', on_delete=django.db.models.deletion.CASCADE, to='georef.Recursgeoref'),
        ),
        migrations.AddField(
            model_name='capesrecurs',
            name='idcapa',
            field=models.ForeignKey(blank=True, db_column='idcapa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='georef.Capawms'),
        ),
        migrations.AddField(
            model_name='capesrecurs',
            name='idrecurs',
            field=models.ForeignKey(blank=True, db_column='idrecurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capes', to='georef.Recursgeoref'),
        ),
        migrations.AddField(
            model_name='autorrecursgeoref',
            name='autor',
            field=models.ForeignKey(db_column='idpersona', on_delete=django.db.models.deletion.CASCADE, to='georef_addenda.Autor'),
        ),
        migrations.AddField(
            model_name='autorrecursgeoref',
            name='recurs',
            field=models.ForeignKey(db_column='idrecursgeoref', on_delete=django.db.models.deletion.CASCADE, to='georef.Recursgeoref'),
        ),
        migrations.AlterUniqueTogether(
            name='autorrecursgeoref',
            unique_together=set([('autor', 'recurs')]),
        ),
    ]
