# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-11-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0002_auto_20230928_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paraulaclau',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualificadorversio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipusrecursgeoref',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipustoponim',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipusunitats',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
