# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2024-11-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import georef_addenda.models


class Migration(migrations.Migration):

    dependencies = [
        ('georef_addenda', '0007_georeferenceprotocol'),
        ('georef', '0003_auto_20241106_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='toponimversio',
            name='georeference_protocol',
            field=models.ForeignKey(default=georef_addenda.models.GeoreferenceProtocol.get_default_pk, on_delete=django.db.models.deletion.DO_NOTHING, to='georef_addenda.GeoreferenceProtocol'),
        ),
    ]
