"""
Django settings for djangoref project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LANGUAGES = (
    ('ca', _('Catalan')),
    ('en', _('English')),
)

LOCALE_PATHS = (
   os.path.join(BASE_DIR, 'locale'),
)

# create language
# django-admin.py makemessages -l en
# django-admin.py makemessages -d djangojs -l en
# django-admin.py makemessages -l ca
# django-admin.py makemessages -d djangojs -l ca
# compile languages
# django-admin.py compilemessages

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY","secret!")

# SECURITY WARNING: don't run with debug turned on in production!
# OVERRIDEN IN SETTINGS_LOCAL
DEBUG=int(os.environ.get("DEBUG", default=0))

# OVERRIDEN IN SETTINGS_LOCAL
ALLOWED_HOSTS=os.environ.get("DJANGO_ALLOWED_HOSTS","*").split(" ")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'bootstrap3',
    'georef',
    'georef_addenda',
    'djangobower',
    'ajaxuploader',
    'datetimewidget',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'georef.middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoref.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'georef.context_processors.revision_number_processor',
                'georef.context_processors.version_number_processor',
                'georef.context_processors.custom_util_links_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoref.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATABASES = {
    'default': {
        'ENGINE': os.environ.get("SQL_ENGINE", 'django.contrib.gis.db.backends.postgis'),
        'NAME': os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "postgres")),
        'USER': os.environ.get("SQL_USER", "postgres"),
        'PASSWORD': os.environ.get("SQL_PASSWORD", ""),
        'HOST': os.environ.get("SQL_HOST", "db"),
        'PORT': os.environ.get("SQL_PORT", "5432")
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/login'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
]

# ./manage.py bower install
BOWER_INSTALLED_APPS = (
    'jquery',
    'jquery-ui',
    'datatables.net',
    'datatables.net-dt',
    'popper.js',
    'bootstrap',
    'toastr',
    'jstree',
    'jquery-tagit',
)

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25
}

MEDIA_URL = '/media/'
# Media root
UPLOAD_DIR = BASE_DIR + "/uploads"
LOCAL_DATAFILE_ROOT_DIRECTORY = 'helpfile_uploads'
MEDIA_ROOT = UPLOAD_DIR
STATIC_ROOT = '/public_html/djangoref/static/'

#GEOSERVER STUFF
#DO NOT CHANGE THIS VALUE!
GEOSERVER_WORKSPACE = 'mzoologia'
GEOSERVER_USER = os.environ.get("GEOSERVER_ADMIN_USER", 'admin')
GEOSERVER_PASSWORD = os.environ.get("GEOSERVER_ADMIN_PASSWORD", 'geoserver')
GEOSERVER_BASE_URL = 'http://127.0.0.1:8080/'
GEOSERVER_WMS_URL_CLEAN = GEOSERVER_BASE_URL + 'geoserver/wms/'
GEOSERVER_REST_URL = GEOSERVER_BASE_URL + 'geoserver/rest/'
GEOSERVER_WMS_URL = GEOSERVER_BASE_URL + 'geoserver/' + GEOSERVER_WORKSPACE + "/wms/?"

# bing developer account a.escobar@creaf.uab.cat
BING_MAPS_API_KEY = os.environ.get("BING_MAPS_API_KEY", "")

#5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760

JAVASCRIPT_VERSION = 1

#Semver versioning - https://semver.org/
MAJOR="1"
MINOR="0"
PATCH="0"

# Links in utilities. Each element is "title","link"
# if title is blank, a separator is inserted
CUSTOM_TOOL_LINKS = (
    (_("Anar a google"), "https://www.google.es"),
    (_("Anar a ICC"), "http://www.icgc.cat/"),
    ("", ""),
    (_("Conversió de coordenades - Convertbox"), "http://betaportal.icgc.cat/convertbox/#"),
    (_("Conversió de coordenades - Earth Point: Convert coordinates"), "http://www.earthpoint.us/Convert.aspx"),
    ("", ""),
    (_("Georeferenciació - Geolocate"), "http://www.geo-locate.org/web/WebGeoref.aspx"),
    (_("Georeferenciació - Georeferencing calculator"), "https://www.gbif.org/tool/81315/georeferencing-calculator"),
    (_("Georeferenciació - Berkeley Mapper"), "http://berkeleymapper.berkeley.edu/#"),
)
